# Generated by Django 5.0.7 on 2024-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bbcode_content',
            field=models.TextField(blank=True, null=True, verbose_name='BBCode содержание'),
        ),
    ]
